# Generated by Django 3.0.8 on 2020-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tab_bords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date ')),
                ('num_mission', models.IntegerField(default=0, verbose_name='num_mission')),
                ('direction', models.CharField(max_length=42)),
                ('Heure_depart', models.DateTimeField(auto_now_add=True, verbose_name='heure_depart')),
                ('compteur_depart', models.IntegerField(default=0, verbose_name='compteur_depart')),
                ('compteur_arriver', models.IntegerField(default=0, verbose_name='compteur_arriver')),
                ('mission', models.CharField(max_length=42)),
                ('Nom_chauffeur', models.CharField(max_length=42)),
                ('Accompagnant', models.CharField(max_length=42)),
                ('Materiels', models.CharField(max_length=42)),
                ('Lieu_carburant', models.CharField(max_length=42)),
                ('Quantite_carbu', models.IntegerField(default=0, verbose_name='quantite_carbu')),
                ('Num', models.IntegerField(default=0, verbose_name='Nombre ')),
                ('Heure_retour', models.DateTimeField(auto_now_add=True, verbose_name='heure_retour')),
            ],
        ),
    ]
