# Generated by Django 3.0.8 on 2020-07-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0002_auto_20200714_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_bords',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
